#!/usr/bin/env bash
# Alias definition
#
# shellcheck disable=SC2154  # v is referenced but not assigned
# shellcheck disable=SC2015  # Note that A && B || C is not if-then-else. C may run when A is true

alias bat="PAGER= bat"
# Helper
  function mcomplete_cmd {
    # Get cmd: first word
    # shellcheck disable=SC2206  # quote
    a_cmd=( $1 )
    cmd=${a_cmd[0]}

    # Get complete function
    # shellcheck disable=SC2207  # Prefer mapfile or read -a to split command output
    line=( $(complete -p "$cmd" 2> /dev/null ) ) || return 1
    fct=${line[-2]}

    # Return function
    echo "$fct"
  }

  function malias {
    # shellcheck disable=SC2139  # This expands when defined => OK
    alias "$1"="$2"
    [[ ! "$os" == "windows" ]] && command -v _completion_loader > /dev/null && _completion_loader "$2"
    fct="$(mcomplete_cmd "$2")"
    [ -n "$fct" ] && complete -F "$fct" "$1" > /dev/null 2>&1
  }



# Shortcut
  # Small as Huffman
  malias f find
  malias g git
  malias v vim
  malias o xdg-open
  malias c clip
  malias m man
  alias h="history | rg "
  alias fr="find . | rg "

  # Little longer
  malias disas 'objdump -drwC -Mintel'
  malias ll 'ls -lh'
  malias so source
  malias ssh 'TMUX= TERM=xterm-256color ssh'

  # Languages
  malias fd fdfind
  malias py python3
  malias py2 python2
  malias py3 python3
  malias pl perl
  malias ra 'raku -I.'
  malias terminal 'TMUX= alacritty'
  malias te 'TMUX= alacritty'
  malias terminal_raw 'alacritty'
  malias traw 'alacritty -e env -i INPUTRC= bash --noprofile --norc'
  malias tnotmux 'alacritty'
  malias vi vim
  alias ipy='jupyter-console'
  alias ira='jupyter-console --kernel=raku'
  alias ija='jupyter-console --kernel=java'

  # Wiki
  # # Completion generated by wiki2html.copy_src
  #function w () { if [[ -z "$1" ]]; then vim -c"call Windex(1)"; else vim -c"call Windex(1)" -c":VimwikiGoto $1"; fi ; }
  #function a () { if [[ -z "$1" ]]; then vim -c"call Windex(3)"; else vim -c"call Windex(3)" -c":VimwikiGoto $1"; fi ; }
  #function t () { if [[ -z "$1" ]]; then vim -c"call Windex(2)"; else vim -c"call Windex(2)" -c":VimwikiGoto $1"; fi ; }
  f="$HOME/wiki/todo/Src/links.txt" ; [ -f "$f" ] && complete -W "$(cat "$f")" t
  f="$HOME/wiki/wiki/Src/links.txt" ; [ -f "$f" ] && complete -W "$(cat "$f")" w

  # New terminal (without tmux)
  alias tnew='TMUX=1 gnome-terminal'

  # TODO traw without any rc for testing

  # Alma
  alias alma_docker='cd ~/Program/Alma/Docker && docker-compose run centos8 bash'

# Fzf
  alias fo=fzf_open
  alias ff=fzf_line
  alias fl=fzf_line
  alias fcd=fzf_cd


# Path variable
  # shopt -s direxpand
  export b="$v/bin" ; export bin="$b"
  export p="$v/pack/bundle/opt/" ; export pack="$p"
  export pw="$v/pack/bundle/opt/wiki"
  export t="$HOME/wiki/todo"
  export vb="$v/bin"
  export vd="$v/dotfile"
  export w="$HOME/wiki/wiki"
  export wt="$HOME/wiki/todo"
  export wa="$HOME/wiki/alma"


# Tmux
  alias tl="tmux list-sessions"
  alias tks='tmux kill-session -t'


# Shortcut largers
  export TRASH="$HOME/.Trash"

  # Bigger for memory
  alias open='xdg-open'
  alias clip="xclip -selection c"
  #alias find="find -not -path '*/\.*'"

  # Utils
  # shellcheck disable=SC2139  # This expands when defined
  alias clean_tex="mv -t $TRASH *.aux *.log *.fls *.fdb_latexmk *.out *synctex.gz *.tex.backup *.4ct *.4tc *.idv *.lg *.tmp *.xref *.xdv *.dvi *.bak *.toc"
  alias clip='xclip -selection c'

  # Safe RM
  # shellcheck disable=SC2139  # This expands when defined, not when used
  alias rm="echo better use trash; mv -f -t $TRASH"
  alias rmv='command rm'
  alias trash="trash-put"

  # CD ..
  alias p='cd ..'
  alias pp='cd ../..'
  alias ppp='cd ../../..'
  alias pppp='cd ../../../..'
  alias ppppp='cd ../../../../..'
  alias pppppp='cd ../../../../../..'


# Color improve (ls, grep)
  if command -v dircolors > /dev/null; then
    [[ -r ~/.dircolors ]] && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  fi
  malias ls 'ls --color=auto'
  malias grep 'grep --color=auto'


# Utils
  # Dropbox
  alias dropbox='~/.dropbox-dist/dropboxd $'

  # Battery
  alias battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage'

  # Diskspace
  alias diskspace="du -S | sort -n -r |more"


# Jump marks from http://jeroenjanssens.com/2013/08/16/quickly-navigate-your-filesystem-from-the-command-line.html
  export MARKPATH=$HOME/.marks
  function jump {
    cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
  }
  function mark {
    mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
  }
  function unmark {
    rm -i "$MARKPATH/$1"
  }
  function marks {
    # shellcheck disable=SC2012  # Use find
    ls -l "$MARKPATH" | sed 's/  / /g' | cut -d' ' -f9- | sed 's/ -/\t-/g' && echo
  }
  function find-text {
    find .  -not -path '*/\.*' -type f  -exec grep -Iq . {} \; -print;
  }
  # alias m="mark"
  # alias ms="marks"
  # alias mj="jump"

