set nocompatible | filetype on | syntax on


" Variable
  " OS
  let $os = 'unknown'
  if has('unix')
    let $os = 'unix'
    let s:tmp = system('uname -a')
    if -1 != match(s:tmp, '\candroid')
      let $os = 'termux'
    endif
  elseif has('win32') || has('win64')
    let $os = 'windows'
  endif

  " Os dependant
  if 'windows' == $os
    let $home = expand("C:/Users/tbf")
    let $alias = expand("H:/Program/Cmder/config/user-aliases.cmd")
  else
    let $home = "~"
  endif

  " Vim
  let $MYVIM = expand($home . '/.vim')
  let $vim = $MYVIM
  let $v = $MYVIM
  let $vimrc = $v . "/dotfile/vimrc"
  let $vimrc = $v . "/dotfile/bashrc"
  let $script = expand("$v/scripts")
  let $s = $script
  let $auto = expand("$v/autoload")
  let $ft = expand("$v/ftplugin")
  let $start = expand("$vim/pack/bundle/start")
  let $opt = expand("$vim/pack/bundle/opt")
  let $dump = expand("$vim/undo/dump")
  let $wiki = expand("~/wiki/wiki")
  let $w = $wiki



" From vim debian team (better at start)
  if filereadable("/etc/vim/vimrc.local")
    source /etc/vim/vimrc.local
  endif


" Source (my broters)
  source $MYVIM/scripts/myfunctions.vim
  source $MYVIM/scripts/cfunctions.vim
  " TODO if gvim
  " source $MYVIM/scripts/fontsize.vim


" Appearance , Color, Search, Set staff
  set diffopt+=vertical
  set guioptions-=T                  " Toolbar
  set guioptions-=m                  " Menumbar
  set encoding=utf-8
  " No auto comment
  set formatoptions-=c
  set formatoptions-=r
  set formatoptions-=o
  set nu
  "SEARCH 
  set ignorecase
  set smartcase
  set ignorecase
  set hlsearch      " highlight search terms
  set incsearch     " show search matches as you type
  " Title and color 
  set title                    " change the terminal's title, may not work
  " Enable CursorLine
  set cursorline
  " Default Colors for CursorLine
  highlight  CursorLine term=underline cterm=underline ctermbg=None ctermfg=None
  "Change Color when entering Insert Mode
  autocmd InsertEnter * highlight  CursorLine term=None cterm=None
  " Revert Color to default when leaving Insert Mode
  autocmd InsertLeave * highlight  CursorLine term=underline cterm=underline ctermbg=None ctermfg=None

  set autoindent  " to have auto indentation when return line 
  colorscheme dante
  set laststatus=2 " for airline
  " WINDOWS 
    set ruler 
    set backspace=2 
    set foldlevelstart=30 "the folding at opening
    set wrap
    set fileformat=unix
    " set shell=H:/Program/cmder-1.2.9/Cmder.exe
  " TAB
    set expandtab
    set shiftwidth=2
    set tabstop=2
    set wrapscan
  " Viminfo rememebr last 10000 opened files
  let s:viminfo=join(map(split(&viminfo, ","), {arg -> (v:val[0] == "'" ? "'10000" : v:val)}), ",")
  exe("set viminfo=" . s:viminfo)


" Backup
  set nobackup                  " I may change that 
  set noswapfile                " I will this if this is harmfull
  set nowritebackup
  set backupdir=~/.vim/backup// " the double // will put the backup with the full directory  
  set directory=~/.vim/backup// " for the swap files 
  set undolevels=10000         " use many levels of undo
  set history=10000    " After nocompatible 
  set autoread                  " when reopening a file, go to the position as when you quit it +  This will disable read-only to writeable warnings
 
  if has('persistent_undo')
    set undodir=$MYVIM/undo
    set undofile 
  endif 


" Mouse Integration
  " Send more characters for redraws
  set mouse=a " Enable mouse use in all modes
  set ttyfast
  set ttymouse=xterm2


" Map
  let mapleader=','
  tnoremap <Esc> <C-W>N

  " Indent < and >
    noremap > >>
    noremap < <<
    vnoremap > >gv 
    vnoremap < <gv 

  " Ctrlz
    nnoremap <silent> <expr> <leader>d ctrlz#dadcd()
    nnoremap <expr> <c-z> ctrlz#ctrlz()

  " Perso maps normal
    nnoremap H :set cursorline! cursorcolumn!<CR> 
    map xy :s/x/y/g<CR>
    map yx :s/y/x/g<CR>

  " Copy paste to from clipboard <- ctrl+p  
    nnoremap <C-y> "+y
    vnoremap <C-y> "+y
    nnoremap <C-p> "+p
    vnoremap <C-p> "+p

  " Command : %% to expand path in command mode  
    cnoremap %% <C-R>=expand('%:p:h').'/'<CR>|  

  " Insert mode begin, end <- c-a c-e shotcuts from gnome
    inoremap <C-A> <C-O>^
    inoremap <C-E> <C-O>g_
    inoremap <C-K> <C-O>D 

  " Esc <- jk or kj
    imap jk <Esc>
    imap kj <Esc>

  " C-Arrow on Ubuntu 
    "Get Ctrl + ARROW KEYS,because if you don't do that, the <C-Up>  (ie crtl + up ) key is notreckognise 
    map [1;5A <C-Up>
    map [1;5B <C-Down>
    map [1;5D <C-Left>
    map [1;5C <C-Right>

    map [1;2D <S-Left>
    map [1;2C <S-Right>
    cmap [1;2D <S-Left>
    cmap [1;2C <S-Right>

  " Save c-s and s
    noremap <C-S>      :update!<CR>
    vnoremap <C-S>    <C-C>:update!<CR>
    inoremap <C-S>    <C-O>:update!<CR>
    map s <C-S>

  " Commenting blocks of code with ,cc ,cu
    autocmd FileType c,cpp,java,scala let b:comment_leader = '// '
    autocmd FileType sh,ruby,python   let b:comment_leader = '# '
    autocmd FileType conf,fstab       let b:comment_leader = '# '
    autocmd FileType tex              let b:comment_leader = '% '
    autocmd FileType mail             let b:comment_leader = '> '
    autocmd FileType vim              let b:comment_leader = '" '
    noremap <silent> ,cc :<C-B>silent <C-E>s/^/<C-R>=escape(b:comment_leader,'\/')<CR>/<CR>:nohlsearch<CR>
    noremap <silent> ,cu :<C-B>silent <C-E>s/^\V<C-R>=escape(b:comment_leader,'\/')<CR>//e<CR>:nohlsearch<CR>

  " Fold 
    nnoremap <space> za
    vnoremap <space> zf
    map z0  :set foldlevel=0<CR><Esc>
    map z1  :set foldlevel=1<CR><Esc>
    map z2  :set foldlevel=2<CR><Esc>
    map z3  :set foldlevel=3<CR><Esc>
    map z4  :set foldlevel=4<CR><Esc>
    map z5  :set foldlevel=5<CR><Esc>
    map z6  :set foldlevel=6<CR><Esc>
    map z7  :set foldlevel=7<CR><Esc>
    map z8  :set foldlevel=8<CR><Esc>
    map z9  :set foldlevel=9<CR><Esc>
    " And for azery
    map z& z1
    map zé z2
    map z" z3
    map z' z4
    map z( z5
    map z- z6
    map zè z7
    map z_ z8
    map zç z9
  
  " Tab
    map g1 :1tabnext<CR><Esc>
    map g2 :2tabnext<CR><Esc>
    map g3 :3tabnext<CR><Esc>
    map g4 :4tabnext<CR><Esc>
    map g5 :5tabnext<CR><Esc>
    map g6 :6tabnext<CR><Esc>
    map g7 :7tabnext<CR><Esc>
    map g8 :8tabnext<CR><Esc>
    map g9 :9tabnext<CR><Esc>
    " And for azery
    map g& g1
    map gé g2
    map g" g3
    map g' g4
    map g( g5
    map g- g6
    map gè g7
    map g_ g8
    map gç g9

  " Edit special files ,v
    nnoremap <Leader>v :try \| b $vimrc \| catch \| e $vimrc \| endtry <CR>
    nnoremap <leader>s :update \| :so %<CR>:echo 'file sourced ' . expand('%')<CR>
    nnoremap <Leader>b :try \| b $bashrc \| catch \| e $bashrc \| endtry <CR>
    " Todo create backup dir
    " nnoremap <leader>b :write! $dump/%:t-<C-R>=strftime("%y%m%d")<CR>-bak.txt<CR>


" Command
  if exists(":Man") != 2
    com! -nargs=+ -complete=shellcmd M ru! ftplugin/man.vim | Man <args>
  else
    com! -nargs=+ -complete=shellcmd M Man <args>
  endif


" Folding
  highlight Folded ctermfg=DarkGreen ctermbg=Black
  set foldignore=
  set foldmethod=indent
  set foldcolumn=0  "the number of columns on the left to show the tree, default =0 
  set foldlevelstart=30 "the folding at opening


" Buffer Management (and it maps)
  "map <Tab> :bnext<cr>
  "map <S-Tab> :bprevious<cr>
  noremap <C-Tab> :BufExplorer<CR>
  " from http://vim.wikia.com/wiki/Easier_buffer_switching
  set wildchar=<Tab> wildmenu wildmode=full
  set wildcharm=<C-Z>
  nnoremap <F10> :b <C-Z>
  " Mappings to access buffers (don't use "\p" because a
  " " delay before pressing "p" would accidentally paste).
  " " \l       : list buffers
  " " \b \f \g : go back/forward/last-used
  " " \1 \2 \3 : go to buffer 1/2/3 etc
  map <Leader>l :ls<CR>
  map <Leader>b :bp<CR>  
  "overwriten by GDB
  map <Leader>f :bn<CR>
  map <Leader>1 :1b<CR>
  map <Leader>2 :2b<CR>
  map <Leader>3 :3b<CR>
  map <Leader>4 :4b<CR>
  map <Leader>5 :5b<CR>
  map <Leader>6 :6b<CR>
  map <Leader>7 :7b<CR>
  map <Leader>8 :8b<CR>
  map <Leader>9 :9b<CR>
  map <Leader>0 :10b<CR>

  map z0 :set foldlevel=0<CR>
  map z1 :set foldlevel=1<CR>
  map z2 :set foldlevel=2<CR>
  map z3 :set foldlevel=3<CR>
  map z4 :set foldlevel=4<CR>
  map z5 :set foldlevel=5<CR>
  map z6 :set foldlevel=6<CR>
  map z7 :set foldlevel=7<CR>


" Filetype
  au BufNewFile,BufRead *.masm      setf masm
  au BufNewFile,BufRead *.asm       setf masm
  au BufNewFile,BufRead *.disarm    setf disarm
  au BufNewFile,BufRead *.kd        setf kd
  au BufNewFile,BufRead */todo      setf vimwiki


" Plugin
  " Pymode
    let g:pymode_python = 'python3'
    " Column at 120
    autocmd FileType python set colorcolumn=120
    let g:pymode_options_colorcolumn = 0 " Remove the red line
    let g:pymode_rope_goto_definition_cmd = 'e'
    " Auto open cwindow (quickfix) if any errors have been found
    let g:pymode_lint_cwindow = 0
    
    " Pylint ignore 
    let s = ""
    let s .= ",E303"  " Too many blank lines
    let s .= ",E501"  " Line too long > 80 
    let s =  ",E701"   " Multiple statement on one line

  " ConqueDbg, a gdb plugging
    let g:ConqueGdb_Disable = 1 
    let g:ConqueTerm_Color = 2         " 1: strip color after 200 lines, 2: always with color
    let g:ConqueTerm_CloseOnEnd = 1    " close conque when program ends running
    let g:ConqueTerm_StartMessages = 0 " display warning messages if conqueTerm is configured incorrectly 
    let g:ConqueTerm_PyVersion = 3

  " Vdebug
    let g:vdebug_keymap = {
    \    "run" : "<F5>",
    \    "close" : "<F6>",
    \    "detach" : "<F7>",
    \    "run_to_cursor" : "<F8>",
    \    "set_breakpoint" : "<F9>",
    \    "step_over" : "<F10>",
    \    "step_into" : "<F11>",
    \    "step_out" : "<F12>",
    \    "get_context" : "<F2>",
    \    "eval_under_cursor" : "<F3>",
    \    "eval_visual" : "<Leader>e",
    \}

  " CtrlP
    " E like edit and closer to ctrl + <c-p> used to paste
    let g:ctrlp_map = '<c-e>'
    " Mixed to search in MRU, FIles, Buffers
    let g:ctrlp_cmd = 'CtrlPMixed'
    " Ctrlp Plugin Buffer with ctrl-b
    map <C-b> :CtrlPBuffer<CR>

  " Vim Translator
    ".vimrc
    " language code iso 639-1
    "? define key in visual-mode (optional)
    let g:goog_user_conf = { 'langpair': 'en|ru', 'cmd': 'node', 'v_key': 'T' }

  " AnsiEsc
    " au BufWinEnter *.a.txt AnsiEsc
    " au BufWinEnter *.a.txt set nowrap | echom "I saw an ansi file"
    " au ColorScheme * AnsiEsc!

  " Emacs Command line
    let g:EmacsCommandLineSearchCommandLineDisable = 1

  " Eclim 
    filetype plugin indent on
    let g:EclimCompletionMethod = 'omnifunc'

  " Vimtex
    " Disable overfull/underfull \hbox
    let g:vimtex_quickfix_latexlog = {
        \ 'overfull' : 0,
        \ 'underfull' : 0,
        \}

  " Ultisnip
    let g:UltiSnipsExpandTrigger="<c-j>"
    let g:UltiSnipsUsePythonVersion = 3

  " Fugitive
    map <leader>gd :Gdiff<CR>
    map <leader>gb :Gblame<CR>
    map <leader>gs :Gstatus<CR>
    map <leader>gl :Glog<CR>
    map <leader>gc :Gcommit -m ""<C-b>
    map <leader>ga :Git add 

  " YouCompleteMe
    " let g:ycm_global_ycm_extra_conf = "~/.vim/pack/bundle/opt/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"

  " Viewdoc
    let g:no_viewdoc_abbrev = 1
    let g:viewdoc_open = "e"

  " Table mode
    let g:table_mode_tableize_map = 'i'

  " Vimwiki
    " Wiki
    let g:vimwiki_list = [{
      \ 'syntax': 'markdown',
      \ 'ext': '.md',
      \ 'custom_wiki2html': $home . "/wiki/wiki/wiki2html.sh",
      \ 'path': $home . '/wiki/wiki',
      \ 'path_html': $home . '/wiki/wiki_html'
      \ }]
    " Todo
    let g:vimwiki_list += [{
      \ 'syntax': 'markdown',
      \ 'ext': '.md',
      \ 'custom_wiki2html': $home . "/wiki/wiki/wiki2html.sh",
      \ 'path': $home . '/wiki/todo',
      \ 'path_html': $home . '/wiki/todo_html'
      \ }]
    map ,t 2,w
    map ,tt 2,ww
    map ,t,t 2,w,w
    let g:vimwiki_table_reduce_last_col = 1
    let g:vimwiki_table_mappings = 0
    let g:vimwiki_table_auto_fmt = 1


    " Termux
    if 'termux' == $os
      autocmd CursorHold,CursorHoldI *  silent update
    endif



  " Ack to use ag
  let g:ackprg = 'ag --vimgrep --smart-case'
  cnoreabbrev ag Ack
  cnoreabbrev aG Ack
  cnoreabbrev Ag Ack
  cnoreabbrev AG Ack


" Fastly (added)
  command! -nargs=0 -bar Helptags for p in glob('~/.vim/pack/bundle/opt/*', 1, 1) | exe 'packadd '.fnamemodify(p, ':t') | endfor | helptags ALL
  packadd perlomni
