---
# Shell check my scripts

name: "Bash"

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # This action is crafting the docker image from the root Docker file
      # or will use it is exists in cache
      # It caches in GHA for GitHub Actions with 10 Gb
      # See: https://github.com/moby/buildkit#github-actions-cache-experimental
      # Examples at: https://github.com/docker/build-push-action/blob/
      # e27bcee4eb9e7b4bc168418e3364c4482120393a/docs/advanced/cache.md
      - name: Docker
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./test/bash.dockerfile
          push: false
          tags: bash_image:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Bash test
        run: |
          pushd test || exit 101

          docker run --name=bash_container bash_image || exit 103
          docker cp bash_test.sh bash_container:/bash_test.sh || exit 104
          docker exec bash_container bash /bash_test.sh || exit 105

          popd || exit 102
