---
# Shell check my scripts

name: Pylint

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  pylint:
    name: Pylint
    # Copied from: https://github.com/pylint-dev/pylint/pull/2758
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip3 install pylint
      - run: pip3 install -U git+https://github.com/tinmarino/abism
      # yamllint disable-line rule:line-length
      - run: pylint --rcfile=.github/res/pylint.rc dotfile/*.py
