---
# Pylint check my python scripts

name: Pylint

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  pylint:
    name: Pylint
    # Copied from: https://github.com/pylint-dev/pylint/pull/2758
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pylint
        run: |
          pip3 install pylint
          pip3 install -U git+https://github.com/tinmarino/abism


      - name: Run pylint
        # yamllint disable-line rule:line-length
        run: pylint --rcfile=.github/res/pylint.rc dotfile/*.py
