---
# Shell check my scripts

name: "Shellcheck"

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: ShellCheck bin
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: --exclude=SC1091,SC2155
        with:
          version: v0.9.0
          ignore_paths: >-
            ./bin/lib/*
            ./bin/shellutil.sh
          scandir: './bin'


      - name: ShellCheck bashrc
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: --exclude=SC1091,SC2155
        with:
          version: v0.9.0
          scandir: ./dotfile/bashrc
