---
# Copied from previous .travis.yml by tinmarino the 2023-03-09

# Commented out to avoid verbosity on github commit status
name: "Vader"

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  Vader:
    name: "Vader: ${{ matrix.os }} ${{ matrix.opt }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        opt: [
          "-n vim_8.1.0519",
          "-n vim_9.0.1396",
          "-n nvim_0.3.8",

          # Cannot quote as it is expanded from $OPT after quote removal
          # So I decided to escape the *
          "-n vim_7.4.1099 -f '[a-k]*.vader'",
          "-n vim_7.4.1546 -f 'l*.vader'",
          "-n vim_8.0.0027 -f '[m-z]*.vader'",
        ]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      # This action is required to fetch the code to test
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # This action is crafting the docker image from the root Docker file
      # or will use it is exists in cache
      # It caches in GHA for GitHub Actions with 10 Gb
      # See: https://github.com/moby/buildkit#github-actions-cache-experimental
      # Examples at: https://github.com/docker/build-push-action/blob/
      # e27bcee4eb9e7b4bc168418e3364c4482120393a/docs/advanced/cache.md
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: vimwiki:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - name: Check
        run: |
          pushd test
            bash run_tests.sh -v -t vader $OPT;
        env:
          OPT: ${{ matrix.opt }}
