---

name: "Vint"

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  Vint:
    # Copied from: https://github.com/LudvigHz/vint-action
    # And local ./test/run_test.sh
    name: Vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ludvighz/vint-action@v1
        with:
          path: dotfile/vimrc
          args: --style-problem
      - uses: ludvighz/vint-action@v1
        with:
          path: autoload
          args: --style-problem
      - uses: ludvighz/vint-action@v1
        with:
          path: after
          args: --style-problem
      - uses: ludvighz/vint-action@v1
        with:
          path: ftplugin
          args: --style-problem
      - uses: ludvighz/vint-action@v1
        with:
          path: ftdetect
          args: --style-problem
